version: '3.0'

services:
    weather_bot:
        build: weather_bot_project/app
        ports:
            - 5000:5000

    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - weather_bot
